### PR TITLE
Visual Regression Tests should be defined in nightwatch config file's globals section

### LINKED ISSUE #14: Running nightwatch in parallel - missing config
When running the vrt plugin in a spawned parallel process the ``nightWatchClient.globals.test_settings.visual_regression_settings`` in ``generate-screenshot-file-path.js`` is empty. I have found a workaround for this by adding it manually to the nightwatch config like so.

```
globals: {
	"waitForConditionTimeout": 5000, // sometimes internet is slow so wait.
	// copied this config here because it seems to be missing when running nightwatch in parallel
	test_settings: {
		visual_regression_settings: {
			"generate_screenshot_path": generateScreenshotFilePath,
			"latest_screenshots_path": "test/vrt/latest",
			"latest_suffix": "",
			"baseline_screenshots_path": "test/vrt/baseline",
			"baseline_suffix": "",
			"diff_screenshots_path": "test/vrt/diff",
			"diff_suffix": "",
			"prompt": false,
			"always_save_diff_screenshot": false,
			"threshold": 0.0
		}
	}
}
```

I'm assuming these properties are not being copied into the global object for some reason when running in parallel but are copied into the global object when running in series. Please advise.

### PR DESCRIPTION
**Pull request by enriquecastl**
Fixes #14

### CODE REVIEW

File: lib/get-vrt-settings.js [hunk 1]
```diff
@@ -10,6 +10,15 @@ const get = require('lodash/get')
  * @return {NightwatchVRTSettings} An object containing the visual regression test settings.
  */
 module.exports = function getVrtSettings(nightwatchClient, overrideSettings) {
+    const visualRegressionSettingsPaths = [
+        'globals.test_settings.visual_regression_settings',
+        'globals.visual_regression_settings'
```
Comment (msteitle) [inline lib/get-vrt-settings.js]: Based on the logic to resolve settings below, it seems like this order should be reversed so that `globals.visual_regression_settings` takes precedence if both are defined (for whatever reason).

File: package.json [hunk 2]
```diff
@@ -8,6 +8,10 @@
         {
             "name": "Connor Schlesiger",
             "email": "connor@schlesiger.ca"
+        },
+        {
+            "name": "Matt Steitle",
+            "email": "msteitle@crunch.io"
```
Comment (msteitle) [inline package.json:14]: Unrelated code change ;)

**Comment by mshing** [comment]
It looks like the same changes need to be made in the generateScreenshotFilePath method to read settings from 'globals.visual_regression_settings'
